### ISSUE TITLE
Fix spelling mistakes/typos in SleeveDecreases.md

### ISSUE THREAD

**Issue by terriko** [terriko/pyknit#3]
I forgot to run a spell check on https://github.com/terriko/pyknit/blob/main/documentation/SleeveDecreases.md and almost certainly left a few typos in.  If someone wants an easy first contribution, run a spell check on that file and fix it up!

**Comment by 96RadhikaJadhav** [comment]
@terriko Can I work on it?

**Comment by terriko** [comment]
Please go ahead! Hopefully it won't be *too* typo ridden.

**Comment by terriko** [comment]
Fixed in #7
