### ISSUE TITLE
Write the decrease_evenly() function

### ISSUE THREAD

**Issue by terriko** [terriko/pyknit#4]
Right now, decrease_evenly is just a stub without any code:

https://github.com/terriko/pyknit/blob/main/pyknit/pyknit.py#L62

it's probably going to be somewhat similar to the sleeve decrease function, with the ability to add padding at the beginning/end of a row.

**Comment by spradhan92** [comment]
I would like to work on this.

**Comment by terriko** [comment]
Have fun!

**Comment by danielsaaf** [comment]
@spradhan92  Are you active on this one? If not, I would like to see if I can contribute here..

**Comment by wilsonify** [comment]
I took a stab at it. PR #51 
I think it can simplified further

https://www.knitgrammer.com/blog/decrease-evenly-calculator
was helpful

**Comment by terriko** [comment]
Closed with #51.  Thank you again, @wilsonify !
